-- AlterTable
ALTER TABLE "User" ADD COLUMN     "dayEndMinutes" INTEGER NOT NULL DEFAULT 1260,
ADD COLUMN     "dayStartMinutes" INTEGER NOT NULL DEFAULT 480,
ADD COLUMN     "workDays" INTEGER[] DEFAULT ARRAY[1, 2, 3, 4, 5]::INTEGER[],
ADD COLUMN     "workEndMinutes" INTEGER NOT NULL DEFAULT 1020,
ADD COLUMN     "workStartMinutes" INTEGER NOT NULL DEFAULT 540;
